renames = {
    "Station": "Station",
    "Status": "Status",
    "Master Incident Number": "Incident_Number",
    "Calltaker Agency": "Calltaker_Agency",
    "Address of Incident": "Address_of_Incident",
    "City": "City",
    "Jurisdiction": "Jurisdiction",
    "Response Area": "Response_Area",
    "Problem": "Problem",
    "Incident Type": "Incident_Type",
    "Response Plan": "Response_Plan",
    "PriorityDescription": "Priority_Description",
    "Alarm Level": "Alarm_Level",
    "Map_Info": "Map_Info",
    "X-Long": "X_Long",
    "Y_Lat": "Y_Lat",
    "ESD02_Shift": "ESD02_Shift",
    "Earliest Time Phone Pickup AFD or EMS": "Phone_Pickup_Time",
    "Incident Time Call Entered in Queue": "Call_Entered_in_Queue",
    "Time First Real Unit Assigned": "First_Unit_Assigned",
    "Time First Real Unit Enroute": "First_Unit_Enroute",
    "Incident Time First Staged": "First_Unit_Staged",
    "Time First Real Unit Arrived": "First_Unit_Arrived",
    "Incident Time Call Closed": "Call_Closed",
    "Last Real Unit Clear Incident": "Last_Unit_Cleared",
    "Earliest Time Phone Pickup to In Queue": "Phone_Pickup_to_In_Queue",
    "In Queue to 1st Real Unit Assigned": "In_Queue_to_1st_Assigned",
    "Earliest Time Phone Pickup to 1st Real Unit Assigned": "Phone_Pickup_to_1st_Assigned",
    "Incident Turnout - 1st Real Unit Assigned to 1st Real Unit Enroute": "1st_Assigned_to_1st_Enroute",
    "Incident Travel Time - 1st Real Unit Enroute to 1st Real Unit Arrived ": "1st_Enroute_to_1st_Arrived",
    "Incident First Unit Response - 1st Real Unit Assigned to 1st Real Unit Arrived": "1st_Assigned_to_1st_Arrived",
    "Earliest Time Phone Pickup to 1st Real Unit Arrived": "Phone_Pickup_to_1st_Arrived",
    "Time Spent OnScene - 1st Real Unit Arrived to Last Real Unit Call Cleared": "1st_Arrived_to_Call_Closed",
    "Incident Duration - Earliest Time Phone Pickup to Last Real Unit Call Cleared": "Phone_Pickup_to_Call_Closed",
    "Incident Call Disposition": "Incident_Call_Disposition",
    "Incident Call Reason": "Incident_Call_Reason",
    "EMS Incident Number/s": "EMS_Incident_Numbers",
    "Radio_Name": "Unit",
    "Department": "Department",
    "Frontline_Status": "Frontline_Status",
    "Location_At_Assign_Time": "Location_At_Assign_Time",
    "FirstAssign": "First_Assign",
    "FirstArrived": "FirstArrived",
    "FirstArrivedEsri": "First_Arrived_Esri",
    "Unit Time Assigned": "Unit_Assigned",
    "Unit Time Enroute": "Unit_Enroute",
    "Unit Time Staged": "Unit_Staged",
    "Unit Time Arrived At Scene": "Unit_Arrived",
    "Unit Time Call Cleared": "Unit_Cleared",
    "In Queue to Unit Dispatch": "In_Queue_to_Unit_Assigned",
    "!!": "Phone_Pickup_to_Unit_Assigned",
    "Unit Dispatch to Respond Time": "Unit_Assigned_to_Enroute",
    "Unit Respond to Arrival": "Unit_Enroute_to_Arrived",
    "Unit Dispatch to Onscene": "Unit_Assigned_to_Arrived",
    "Earliest Phone Pickup Time to Unit Arrival": "Phone_Pickup_to_Unit_Arrived",
    "Unit Assign To Clear Call Time": "Unit_Assign_to_Cleared",
    "Unit OnScene to Clear Call": "Unit_Arrived_to_Cleared",
    "Unit Call Disposition": "Unit_Disposition",
    "Unit Cancel Reason": "Unit_Cancel_Reason",
    "Unit Type": "Unit_Type",
    "Bucket Type": "Bucket_Type",
    "Concurrent Usage": "Unit_Usage_At_Time_of_Alarm",
    "IsESD17": "IsESD17",
    "isETJ": "isETJ",
    "People/Mile": "People_Per_Mile",
    "Population Classification": "Population_Classification",
    "Assigned at Station": "Assigned_at_Station",
    "Distance to S01 in miles": "Distance_to_S01_in_miles",
    "Distance to S02 in miles": "Distance_to_S02_in_miles",
    "Distance to S03 in miles": "Distance_to_S03_in_miles",
    "Distance to S04 in miles": "Distance_to_S04_in_miles",
    "Closest Station": "Closest_Station",
    "Is Closest Station": "Is_Closest_Station",
    "Earliest Time Phone Pickup to In Queue Formatted": "Phone_Pickup_to_In_Queue_Formatted",
    "In Queue to 1st Real Unit Assigned Formatted": "In_Queue_to_1st_Assigned_Formatted",
    "Earliest Time Phone Pickup to 1st Real Unit Assigned Formatted": "Phone_Pickup_to_1st_Assigned_Formatted",
    "Incident Turnout - 1st Real Unit Assigned to 1st Real Unit Enroute Formatted": "1st_Assigned_to_1st_Enroute_Formatted",
    "Incident Travel Time - 1st Real Unit Enroute to 1st Real Unit Arrived  Formatted": "1st_Enroute_to_1st_Arrived_Formatted",
    "Incident First Unit Response - 1st Real Unit Assigned to 1st Real Unit Arrived Formatted": "1st_Assigned_to_1st_Arrived_Formatted",
    "Earliest Time Phone Pickup to 1st Real Unit Arrived Formatted": "Phone_Pickup_to_1st_Arrived_Formatted",
    "Time Spent OnScene - 1st Real Unit Arrived to Last Real Unit Call Cleared Formatted": "1st_Arrived_to_Call_Closed_Formatted",
    "Incident Duration - Earliest Time Phone Pickup to Last Real Unit Call Cleared Formatted": "Phone_Pickup_to_Call_Closed_Formatted",
    "In Queue to Unit Dispatch Formatted": "In_Queue_to_Unit_Assigned_Formatted",
    "!!": "Phone_Pickup_to_Unit_Assigned_Formatted",
    "Unit Dispatch to Respond Time Formatted": "Unit_Assigned_to_Enroute_Formatted",
    "Unit Respond to Arrival Formatted": "Unit_Enroute_to_Arrived_Formatted",
    "Unit Dispatch to Onscene Formatted": "Unit_Assigned_to_Arrived_Formatted",
    "Earliest Phone Pickup Time to Unit Arrival Formatted": "Phone_Pickup_to_Unit_Arrived_Formatted",
    "Unit Assign To Clear Call Time Formatted": "Unit_Assign_to_Cleared_Formatted",
    "Unit OnScene to Clear Call Formatted": "Unit_Arrived_to_Cleared_Formatted",
    "Month": "Month",
    "Year": "Year",
    "Calls > 20 Min - PU to Arrive": "Calls_Over_20_Min",
    "Ph_PU2_UnitArrive Time_Intervals in seconds": "Ph_PU_to_Unit_Arrive_Time_Intervals",
    "Incident Call Count": "Incident_Call_Count",
    "Unit Response Single_vs_Multi Response Count": "Unit_Response_Single_vs_Multi_Response_Count",
    "Single_vs_Multi Units ONSC": "Single_vs_Multi_Units_ONSC",
    "Qtr Year": "Qtr_Year",
    "Incident ERF Time": "Incident_ERF_Time",
    "Force At ERF Time or Close": "Force_At_ERF_Time_of_Close",
}


def rename(df):
    return df.rename(columns=renames, errors="ignore")
